name: sticky_notes
description: Sticky Notes - Simple Version
publish_to: 'none'
version: 1.1.3+5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.11
  shared_preferences: ^2.2.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/